### ISSUE TITLE
This dependency was not found

### ISSUE THREAD

**Issue by tomieric** [vadimdemedes/thememirror#2]
```bash
This dependency was not found:

* thememirror in ./src/common/composable/useCodeMirror.js

To install it, you can run: npm install --save thememirror
```

I can fix it like this

```js
import { solarizedLight } from 'thememirror/dist/index';
```

Do You consider adding it

```js
// package.json
{
   "main": "./dist/index.js"
}
```

**Comment by vadimdemedes** [comment]
Hey, `thememirror` package is ESM only, that's why you are unable to import it. I would really like to keep it that way to avoid a separate build for CJS.

See https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c for more details.

**Comment by broofa** [comment]
[Edit: see https://github.com/vadimdemedes/thememirror/issues/2#issuecomment-3042127182]

~~Hi @vadimdemedes, please consider reopening this issue.~~

~~Adding a "`main`" field does not mean your code can't be ESM only, and provides backward compatibility for legacy bundlers like `webpack@4`.~~

~~BTW, there is precedent for this in other popular modules.  The `chalk` project (used by 20M projects) switched to ESM-only in version 5 and provides both `main` and `exports` fields in its [package.json](https://github.com/chalk/chalk/blob/main/package.json#L9-L10).~~

----
FWIW, I landed here because this issue broke our `webpack@4` build with this error:
```
ERROR in ../packages/codemirror/dist/constants/themes.js
Module not found: Error: Can't resolve 'thememirror' in '${PROJECT_DIR}/codemirror'
<snip>
wdm: Failed to compile.
```

**Comment by shshaw** [comment]
To clarify: there's no additional build necessary. Just adding `"main": "./dist/index.js"` to the package.json as-is fixes the package for webpack 4.

**Comment by broofa** [comment]
Withdrawing my support for this after reconsideration.

The `main` field is for documenting the CJS entry point.  Including it in ESM-only packages is semantically incorrect.  Furthermore, @sindresorhus (maintainer of 1,000+ NPM modules) no longer provides a `main` field in any of his ESM-only packages.

While this does keep legacy tools (such as webpack@4) from breaking, fixing that problem shouldn't be the job of module maintainers.
